openapi: 3.0.3
info:
  title: WOO Search
  version: 0.1.0
  description: |2

    The WOO Search API provides an interface to the underlying Elastic Search index.

    Through this API, it's possible to add published documents to the API, or to
    schedule removal of a publication in case it's being retracted. When a supported
    file type is provided, the content of the document itself will also be indexed.

    **Authentication**

    TODO - not implemented yet!

    This API makes use of API Key authentication. All requests must have the
    `Authorization: token <token-value>` HTTP header, where `<token-value>` is
    replaced with the actual API key. API keys are managed in the admin interface,
    and you obtain one by contacting the administrator(s).

    **Audit logging**

    TODO - not implemented yet!

    Audit logging is done at the request level. Clients must send the respective
    HTTP request headers, and the values in those headers will be recorded in the
    audit logs.
  contact:
    url: https://github.com/GeneriekPublicatiePlatformWoo/search
    email: support@maykinmedia.nl
  license:
    name: EUPL
    url: https://github.com/GeneriekPublicatiePlatformWoo/search/blob/main/LICENSE.md
paths: {}
components: {}
externalDocs:
  description: Functional and technical documentation
  url: https://woo-search.readthedocs.io/
